# Generated by Django 4.0.4 on 2022-06-08 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Id', models.CharField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('precio', models.CharField(max_length=20, verbose_name='precio')),
                ('stock', models.CharField(max_length=4, verbose_name='stock')),
                ('descripcion', models.CharField(max_length=80, verbose_name='descripcion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
