# Generated by Django 4.0.4 on 2022-06-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
